#!/usr/bin/env python3
"""Seven real supported programs, per-site identities and exact reachable union. LOCAL ONLY."""
import argparse
import copy
import json
import os
from pathlib import Path
import shutil
import sys

from dependency_wire import read, require
from cfg_wire_contract import verify as verify_cfg_wire
from e2e_w2d import execute, runtime, source_spans
from prepare_w2d_producers import ROOT, git, require_local

FIXTURES = ROOT / 'analysis-adapters/src/test/resources/cp6/multi-call'
# Independent product oracles from the specification, never generated by a solver.
SITES = {
    1: [{'PROGA'}, {'PROGB'}, {'PROGC'}],
    2: [{'PROGA', 'PROGB'}, {'PROGC'}],
    3: [{'PROGA', 'PROGB'}, {'PROGC', 'PROGD'}, {'PROGE'}],
    4: [{'PROGA'}, {'PROGB'}, {'PROGC'}],
    5: [{'PROGA'}, {'PROGB', 'PROGC'}, {'PROGD'}],
    6: [{'PROGA', 'PROGB'}, {'PROGC'}],
    7: [{'PROGA'}, {'PROGB'}, {'PROGA'}],
}
GLOBAL = {1: {'PROGA', 'PROGB', 'PROGC'}, 2: {'PROGA', 'PROGB', 'PROGC'},
          3: {'PROGA', 'PROGB', 'PROGC', 'PROGD', 'PROGE'}, 4: {'PROGA', 'PROGB', 'PROGC'},
          5: {'PROGA', 'PROGB', 'PROGC', 'PROGD'}, 6: {'PROGA', 'PROGB', 'PROGC'}, 7: {'PROGA', 'PROGB'}}


def program_candidates(result):
    reachable = {json.dumps(s['operation'], sort_keys=True) for s in result['sites'] if s['reachability'] == 'REACHABLE'}
    return sorted({e['candidate']['referenceName'] for e in result['edges'] if json.dumps(e['site'], sort_keys=True) in reachable})


def source_oracle(sp, case):
    require(sp['contractVersion'] == '1.7.0' and sp['unit']['canonicalProgramName'] == 'CALLER', 'SP1.7 real CALLER')
    facts = {s['header']['id']: s for s in sp['statements']}
    require(len(facts) == len(sp['statements']) and all(s['header']['coverage'] == 'MODELED' for s in facts.values()), 'complete typed source facts')
    require(all(s['variant'] in {'MOVE', 'CALL', 'IF', 'PERFORM', 'GOBACK'} for s in facts.values()), 'no unknown statement filtering')
    root, seen, calls = sp['entryInventory']['entries'][0]['start']['statement'], set(), []
    while True:
        require(root not in seen, 'closed acyclic primary continuations'); seen.add(root)
        s = facts[root]; require(s['header']['containment'] == {'branch': 'ROOT', 'parent': None}, 'primary root membership')
        if s['variant'] == 'CALL': calls.append(s)
        if s['variant'] == 'GOBACK': break
        require(s['normalContinuation']['availability'] == 'KNOWN', 'known explicit primary continuation')
        root = s['normalContinuation']['statement']
    require(len(calls) == len(SITES[case]), 'all expected source CALLs')
    require(len(calls) == sum(s['variant'] == 'CALL' for s in facts.values()), 'no source CALL omitted')
    performs = [s for s in facts.values() if s['variant'] == 'PERFORM']
    require(len(performs) == (1 if case in (4, 5, 6) else 0), 'MULTI-CALL is not MULTI-PERFORM')
    for p in performs:
        require(p['profile'] == 'SIMPLE_SINGLE_CALLSITE_PROCEDURE_PERFORM' and not p['gapCodes'], 'isolated activation')
        require(set(p['primaryStatements']) == seen and set(p['targetStatements']).isdisjoint(seen), 'complete direct primary and separate target')
        seen.update(p['targetStatements'])
        require(facts[p['targetExit']]['normalContinuation']['statement'] == p['normalContinuation']['statement'], 'body returns to unique resume')
    seen.update(s['header']['id'] for s in facts.values() if s['header']['containment']['parent'] is not None)
    require(seen == set(facts), 'full source inventory accounted for')
    return facts, calls


def air_oracle(air, sp, semantic):
    facts, calls = semantic; p = air['publication']; unit = p['units'][0]
    require(air['airVersion'] == '2.0.0' and air['bindingVersion'] == '1.0.0', 'unchanged AIR wire')
    operations = {}
    labels = {s['label']['localId']: s for s in unit['sequences']}
    for seq in unit['sequences']:
        for offset, op in enumerate(seq['instructions'] + [seq['terminator']]):
            key = op['header']['id']['localId']; require(key not in operations, 'distinct operation identities')
            operations[key] = seq, offset, op
    links = {}
    for ident, fact in facts.items():
        items = [i for i in p['coverage']['items'] if i['sourceKey'].endswith('/' + ident)]
        outputs = [o for i in items for o in i['outputs'] if o['domain'] == 'operation']
        require(len(outputs) == 1, 'one correlated source operation: ' + ident)
        links[ident] = operations[outputs[0]['localId']]
    entry = sp['entryInventory']['entries'][0]['start']['statement']
    require(unit['entries'][0]['initialLabel'] == links[entry][0]['label'], 'explicit entry preserved')
    for ident, fact in facts.items():
        seq, offset, op = links[ident]; kind = fact['variant']
        require(op['kind'] == {'MOVE': 'assign', 'CALL': 'invoke', 'IF': 'branch', 'PERFORM': 'jump', 'GOBACK': 'return'}[kind], 'existing AIR operation per typed statement')
        if kind == 'MOVE':
            target_seq, target_offset, _ = links[fact['normalContinuation']['statement']]
            require(offset < len(seq['instructions']), 'MOVE is instruction')
            if target_seq == seq: require(target_offset == offset + 1, 'MOVE next instruction/terminator')
            else: require(seq['terminator']['kind'] == 'jump' and seq['terminator']['destination'] == target_seq['label'], 'MOVE arm/body explicit completion')
        elif kind == 'CALL':
            require(offset == len(seq['instructions']) and op is seq['terminator'], 'one Invoke terminates each CALL sequence')
            require(op['outcomes']['known'] == [{'kind': 'normal', 'label': links[fact['normalContinuation']['statement']][0]['label']}], 'published CALL continuation')
        elif kind == 'IF':
            for arm, destination in (('thenArm', 'trueDestination'), ('elseArm', 'falseDestination')):
                entry = fact[arm]['entry']['statement'] or fact['normalContinuation']['statement']
                require(op[destination] == links[entry][0]['label'], 'independent IF arm destination')
        elif kind == 'PERFORM':
            body = links[fact['targetEntry']][0]
            require(op['destination'] == body['label'], 'PERFORM enters target')
            require([i['header']['id'] for i in body['instructions']] == [links[s][2]['header']['id'] for s in fact['targetStatements']], 'entire target body in published order')
            require(body['terminator']['kind'] == 'jump' and body['terminator']['destination'] == links[fact['normalContinuation']['statement']][0]['label'], 'PERFORM unique resume')
    require(sum(s['terminator']['kind'] == 'invoke' for s in unit['sequences']) == len(calls), 'all CALLs and no synthetic dependency sites')
    return unit, links


def dependency_oracle(result, air, sp, case, source):
    semantic = source_oracle(sp, case); facts, calls = semantic; unit, links = air_oracle(air, sp, semantic)
    by_operation = {s['operation']['localId']: s for s in result['sites']}
    require(len(by_operation) == len(result['sites']) == len(calls), 'all unique CALL sites')
    require(len(result['edges']) == sum(map(len, SITES[case])), 'one edge per site/candidate')
    for call, expected in zip(calls, SITES[case]):
        seq, offset, invoke = links[call['header']['id']]; site = by_operation[invoke['header']['id']['localId']]
        require(site['operation'] == invoke['header']['id'] and site['sequence'] == seq['label'] and site['offset'] == offset, 'site operation/sequence/offset identity')
        require(site['caller'] == unit['id'] and site['entry'] == unit['entries'][0]['id'] and site['reachability'] == 'REACHABLE', 'reachable caller/entry')
        computed = invoke['target']['kind'] == 'computed'
        require(site['targetKind'] == ('COMPUTED' if computed else 'LITERAL'), 'site-specific target kind')
        require({c['referenceName'] for c in site['candidates']} == expected and len(site['candidates']) == len(expected), 'exact candidates for ' + call['header']['id'])
        if computed:
            require(site['valuePoint'] == {'entryId': site['entry'], 'operationId': site['operation'], 'outcome': None, 'position': 'BEFORE'}, 'point-sensitive value query')
            require(site['subject'] == invoke['target']['name']['place']['object'], 'query subject is this CALL target')
        else: require(site['valuePoint'] is None and site['subject'] is None, 'literal has no value query')
        # Real CALL effects remain conservative. Fixture7 retains a snapshot known value
        # across intervening external calls, with model remainder opened by may-write.
        expected_model_open = case == 7 and call == calls[-1]
        require(site['modelValueRemainder'] is expected_model_open, 'per-site model remainder is preserved')
        require(site['sourceValueRemainder'] and site['interpretationUnknownRemainder'] and site['effectiveUnknownRemainder'], 'source/interpretation/effective remainders remain per-site')
        require(site['openControlRemainder'], 'external control remains open')
        edges = [e for e in result['edges'] if e['site'] == site['operation']]
        require([e['candidate'] for e in edges] == site['candidates'] and all(e['caller'] == site['caller'] for e in edges), 'edges retain each site and its supports')
        for candidate in site['candidates']:
            name = candidate['referenceName']; require(candidate['rawValue'] == (name.ljust(8) if computed else name), 'raw literal/padded value')
            producers = [s for s in facts.values() if s['variant'] == 'MOVE' and s['source']['variant'] == 'LITERAL' and s['source']['logicalValue']['value'] == name] if computed else [call]
            require(len(producers) == 1, 'independent fixture producer identity')
            producer = links[producers[0]['header']['id']][2]; support = candidate['supports']
            require(len(support) == 1 and support[0]['producer'] == producer['header']['id'], 'support cannot cross sites/diamonds')
            require(support[0]['kind'] == ('VALUE_PRODUCER' if computed else 'CALL_LITERAL'), 'specific provenance kind')
            if computed: require(support[0]['origin'] == producer['header']['origin'], 'original literal MOVE support even through copy/PERFORM')
            expected_line = producers[0]['header']['provenance']['original']['startLine']
            spans = source_spans(result, support[0], source)
            require(spans and all(int(s['startLine']) == expected_line == int(s['endLine']) for s in spans), 'support exact source occurrence')
            if computed:
                raw = next(c for c in site['rawCandidates'] if c['rawValue'] == candidate['rawValue'])
                require(raw['supports'] == support, 'raw/interpreted support identity')
    require(program_candidates(result) == sorted(GLOBAL[case]), 'exact global distinct reachable candidate set')
    dynamic = sum(links[c['header']['id']][2]['target']['kind'] == 'computed' for c in calls)
    require(result['metrics']['possibleValuesRuns'] == 1 and result['metrics']['possibleValuesPreparations'] == 1, 'one PossibleValues run/preparation per entry')
    require(result['metrics']['reachabilityRuns'] == 1, 'one shared reachability run')
    require(result['metrics']['planning.uniqueQueries'] == len(calls) + dynamic, 'N reach queries plus D point queries, none for literals')
    return [by_operation[links[c['header']['id']][2]['header']['id']['localId']] for c in calls]


def w1_regressions(work, producer, config, cp):
    for name in ('literal', 'dynamic-x8', 'dynamic-no-move'):
        outputs = []
        for attempt in ('A', 'B'):
            cwd = work / ('w1-' + name + '-' + attempt); cwd.mkdir()
            source = cwd / (name + '.cbl')
            shutil.copyfile(producer / 'cobol-lower/adapters/src/test/resources/sp/cp6' / source.name, source)
            web = cwd / 'src/main/resources'; web.mkdir(parents=True)
            (web / 'web').symlink_to(producer / 'proleap-poc/src/main/resources/web', target_is_directory=True)
            execute(cwd, 'frontend', ['java', '-cp', os.pathsep.join(config['frontend']['classpath']), config['frontend']['main'], '--source', source.name, '--copybooks', str(producer / 'proleap-poc/corpus/cpy'), '--output', str(cwd / 'sp')])
            sp = cwd / 'sp/cobol-semantic-product.json'; air = cwd / 'program.air.json'; cfg = cwd / 'cfg.json'; dep = cwd / 'dependencies.json'
            require(json.loads(sp.read_text())['contractVersion'] == '1.7.0', 'current pinned W1 SP')
            execute(cwd, 'lower', ['java', '-cp', os.pathsep.join(config['lower']['classpath']), config['lower']['main'], str(sp), str(air)])
            execute(cwd, 'cfg', ['java', '-cp', cp, 'io.github.gustavo2358.analysis.cfg.launcher.AnalysisCfg', str(air), str(cfg)])
            verify_cfg_wire(cfg.read_bytes())
            execute(cwd, 'dependency', ['java', '-cp', cp, 'io.github.gustavo2358.analysis.launcher.AnalysisDependencies', str(air), str(dep)])
            result = read(dep); unit = json.loads(air.read_text())['publication']['units'][0]
            sequence = next(s for s in unit['sequences'] if s['terminator']['kind'] == 'invoke'); invoke = sequence['terminator']
            require(len(result['sites']) == 1, 'W1 one site'); site = result['sites'][0]
            require(site['operation'] == invoke['header']['id'] and site['sequence'] == sequence['label'] and site['offset'] == len(sequence['instructions']), 'W1 exact site identity')
            expected = [] if name == 'dynamic-no-move' else ['PROGA']
            require(program_candidates(result) == expected and [c['referenceName'] for c in site['candidates']] == expected, 'W1 known target/open empty regression')
            require(site['modelValueRemainder'] is (name == 'dynamic-no-move'), 'W1 per-site model remainder')
            require(site['sourceValueRemainder'] and site['interpretationUnknownRemainder'] and site['effectiveUnknownRemainder'], 'W1 remainders retained')
            require(result['metrics']['possibleValuesRuns'] == (0 if name == 'literal' else 1), 'W1 literal zero values analyses')
            if name == 'dynamic-x8':
                assign = sequence['instructions'][0]; candidate = site['candidates'][0]
                require(candidate['rawValue'] == 'PROGA   ' and candidate['supports'][0]['producer'] == assign['header']['id'], 'W1 padded value and original producer')
            outputs.append([p.read_bytes() for p in (sp, air, cfg, dep)])
        require(outputs[0] == outputs[1], 'W1 A/B exact bytes ' + name)
        print('PASS current pinned W1 ' + name + ': A/B SP/AIR/CFG/dependency', flush=True)


def run(work, config_path):
    require_local(); work.mkdir(parents=True, exist_ok=False)
    producer = config_path.parent; config = json.loads(config_path.read_text()); lock = json.loads((ROOT / 'docs/sources/sources.lock.json').read_text())
    for name, key in (('air-java', 'air_java'), ('proleap-poc', 'proleap_poc'), ('cobol-lower', 'cobol_lower')):
        pin = lock[key].get('commit', lock[key].get('main_commit'))
        require(config['sources'][name] == pin == git(producer / name, 'rev-parse', 'HEAD') and not git(producer / name, 'status', '--porcelain'), 'exact clean source pin: ' + name)
    require(config['semanticProductVersion'] == lock['proleap_poc']['semantic_product_version'] == '1.7.0', 'exact producer version')
    cp = runtime(producer)
    w1_regressions(work, producer, config, cp)
    for case in SITES:
        outputs = []
        for attempt in ('A', 'B'):
            cwd = work / f'fixture-{case}-{attempt}'; cwd.mkdir(); source = cwd / f'fixture-{case}.cbl'; shutil.copyfile(FIXTURES / source.name, source)
            web = cwd / 'src/main/resources'; web.mkdir(parents=True); (web / 'web').symlink_to(producer / 'proleap-poc/src/main/resources/web', target_is_directory=True)
            execute(cwd, 'frontend', ['java', '-cp', os.pathsep.join(config['frontend']['classpath']), config['frontend']['main'], '--source', source.name, '--copybooks', str(producer / 'proleap-poc/corpus/cpy'), '--output', str(cwd / 'sp')])
            sp_path = cwd / 'sp/cobol-semantic-product.json'; sp = json.loads(sp_path.read_text()); source_oracle(sp, case)
            air_path = cwd / 'program.air.json'; execute(cwd, 'lower', ['java', '-cp', os.pathsep.join(config['lower']['classpath']), config['lower']['main'], str(sp_path), str(air_path)])
            air = json.loads(air_path.read_text()); cfg = cwd / 'cfg.json'; dep = cwd / 'dependencies.json'
            execute(cwd, 'cfg', ['java', '-cp', cp, 'io.github.gustavo2358.analysis.cfg.launcher.AnalysisCfg', str(air_path), str(cfg)])
            verify_cfg_wire(cfg.read_bytes())
            execute(cwd, 'dependency', ['java', '-cp', cp, 'io.github.gustavo2358.analysis.launcher.AnalysisDependencies', str(air_path), str(dep)])
            result = read(dep); sites = dependency_oracle(result, air, sp, case, source)
            if case in (3, 5, 6):
                permuted = copy.deepcopy(air); permuted['publication']['units'][0]['sequences'].reverse()
                perm_air = cwd / 'permuted.air.json'; perm_air.write_text(json.dumps(permuted)); perm_dep = cwd / 'permuted.dependencies.json'
                execute(cwd, 'permuted', ['java', '-cp', cp, 'io.github.gustavo2358.analysis.launcher.AnalysisDependencies', str(perm_air), str(perm_dep)])
                other = read(perm_dep); dependency_oracle(other, permuted, sp, case, source)
                require(result['sites'] == other['sites'] and result['edges'] == other['edges'] and program_candidates(result) == program_candidates(other), 'physical AIR sequence reversal invariant')
            print(f'FIXTURE {case} {attempt}\nCALL SITES', flush=True)
            for n, site in enumerate(sites, 1): print(f'site-{n}:\n  ' + '\n  '.join(c['referenceName'] for c in site['candidates']))
            print('PROGRAM DEPENDENCIES\n' + '\n'.join(program_candidates(result)), flush=True)
            outputs.append([p.read_bytes() for p in (sp_path, air_path, cfg, dep)])
        require(outputs[0] == outputs[1], f'fixture {case} A/B bytes differ')
        print(f'PASS fixture {case}: exact per-site candidates/supports/remainders, global union, batching; A/B SP/AIR/CFG/dependency bytes identical', flush=True)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__); parser.add_argument('--work', type=Path, required=True); parser.add_argument('--producers', type=Path, required=True)
    args = parser.parse_args()
    try: run(args.work.resolve(), args.producers.resolve())
    except (ValueError, RuntimeError, OSError) as error: print('FAIL: ' + str(error), file=sys.stderr); sys.exit(1)
